
precompile(Tuple{typeof(InMemoryDatasets._preprocess_column), Array{Int64, 1}, Int64, Bool})
precompile(Tuple{typeof(InMemoryDatasets._preprocess_column), Array{Float64, 1}, Int64, Bool})
precompile(Tuple{typeof(InMemoryDatasets._preprocess_column), PooledArrays.PooledArray{String, UInt32, 1, Array{UInt32, 1}}, Int64, Bool})
precompile(Tuple{typeof(InMemoryDatasets.hp_maximum), Function, Array{String, 1}})
precompile(Tuple{typeof(Core.Compiler.return_type), Any, Any})
precompile(Tuple{typeof(Core.Compiler.return_type), Any, Any, UInt64})
precompile(Tuple{typeof(Core.Compiler.return_type), Core.Compiler.NativeInterpreter, Any, Any})
precompile(Tuple{typeof(Core.Compiler.contains_is), Core.SimpleVector, Any})
precompile(Tuple{typeof(Base.Threads.threading_run), Function})
precompile(Tuple{typeof(InMemoryDatasets.groupby!), InMemoryDatasets.Dataset, Int64})
precompile(Tuple{typeof(InMemoryDatasets._apply_by), Array{Union{Base.Missing, Int64}, 1}, Array{Int32, 1}, Function, Bool})
precompile(Tuple{typeof(InMemoryDatasets._apply_by_f_barrier), Array{Union{Base.Missing, Int64}, 1}, typeof(Base.identity), Bool})

precompile(Tuple{typeof(InMemoryDatasets.hp_minimum), Array{Union{Base.Missing, Int64}, 1}})
precompile(Tuple{typeof(InMemoryDatasets.hp_minimum), Function, Array{Union{Base.Missing, Int64}, 1}})
precompile(Tuple{typeof(InMemoryDatasets.hp_ds_sort_int!), Array{Union{Base.Missing, Int64}, 1}, Array{Int32, 1}, Array{Int32, 1}, Array{Array{Int32, 1}, 1}, Int64, Int64, Bool, Base.Sort.QuickSortAlg, Base.Order.ForwardOrdering})
precompile(Tuple{typeof(InMemoryDatasets._fill_starts_v2!), Array{Int32, 1}, Array{Bool, 1}, Array{Union{Base.Missing, Int64}, 1}, Int32, Base.Order.ForwardOrdering, Base.Val{Int32}})
precompile(Tuple{typeof(InMemoryDatasets._permute_ds_after_sort!), InMemoryDatasets.Dataset, Array{Int32, 1}})
precompile(Tuple{typeof(InMemoryDatasets._threaded_permute), Array{Union{Base.Missing, Int64}, 1}, Array{Int32, 1}})
precompile(Tuple{typeof(InMemoryDatasets._threaded_permute), Array{Union{Base.Missing, Float64}, 1}, Array{Int32, 1}})
precompile(Tuple{typeof(InMemoryDatasets._threaded_permute), Array{Union{Base.Missing, Dates.Date}, 1}, Array{Int32, 1}})
precompile(Tuple{typeof(InMemoryDatasets._apply_by), Array{Union{Base.Missing, Float64}, 1}, Array{Int32, 1}, Function, Bool})
precompile(Tuple{typeof(InMemoryDatasets._apply_by_f_barrier), Array{Union{Base.Missing, Float64}, 1}, typeof(Base.identity), Bool})
precompile(Tuple{Type{Array{Union{Base.Missing, Float64}, 1}}, UndefInitializer, Int64})

precompile(Tuple{typeof(InMemoryDatasets.hp_ds_sort!), Array{Union{Base.Missing, Float64}, 1}, Array{Int32, 1}, Base.Sort.QuickSortAlg, Base.Order.ForwardOrdering})
precompile(Tuple{typeof(InMemoryDatasets._fill_starts_v2!), Array{Int32, 1}, Array{Bool, 1}, Array{Union{Base.Missing, Float64}, 1}, Int32, Base.Order.ForwardOrdering, Base.Val{Int32}})
precompile(Tuple{typeof(DataAPI.refpool), PooledArrays.PooledArray{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, UInt32, 1, Array{UInt32, 1}}})
precompile(Tuple{typeof(Base.copy), PooledArrays.PooledArray{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, UInt32, 1, Array{UInt32, 1}}})
precompile(Tuple{typeof(Base.getproperty), PooledArrays.PooledArray{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, UInt32, 1, Array{UInt32, 1}}, Symbol})

precompile(Tuple{typeof(InMemoryDatasets._apply_by), Array{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, 1}, Array{Int32, 1}, Function, Bool})
precompile(Tuple{typeof(InMemoryDatasets._apply_by_f_barrier), Array{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, 1}, typeof(Base.identity), Bool})
precompile(Tuple{Type{Array{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, 1}}, UndefInitializer, Int64})

precompile(Tuple{typeof(InMemoryDatasets._permute_ds_after_sort!), InMemoryDatasets.Dataset, Array{Int32, 1}})
precompile(Tuple{typeof(InMemoryDatasets._threaded_permute), Array{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, 1}, Array{Int32, 1}})

precompile(Tuple{Type{InMemoryDatasets.DatasetColumn{T, E} where E where T<:InMemoryDatasets.AbstractDataset}, Int64, InMemoryDatasets.Dataset, Array{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, 1}})
precompile(Tuple{typeof(Base.map), Function, Array{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, 1}})

precompile(Tuple{typeof(InMemoryDatasets.hp_minimum), Array{UInt32, 1}})
precompile(Tuple{typeof(InMemoryDatasets.hp_minimum), Function, Array{UInt32, 1}})
precompile(Tuple{Type{Array{UInt32, 1}}, UndefInitializer, Int64})

precompile(Tuple{typeof(Base.sortperm), InMemoryDatasets.Dataset, Base.UnitRange{Int64}})

precompile(Tuple{typeof(Base.sortperm), InMemoryDatasets.Dataset, Array{Int64, 1}})
precompile(Tuple{typeof(Base.sortperm), InMemoryDatasets.Dataset, Array{Symbol, 1}})
precompile(Tuple{typeof(InMemoryDatasets.groupby!), InMemoryDatasets.Dataset, Base.UnitRange{Int64}})
precompile(Tuple{typeof(InMemoryDatasets._threaded_permute), Array{Union{Base.Missing, Int64}, 1}, Array{Int32, 1}})
precompile(Tuple{typeof(InMemoryDatasets._threaded_permute), Array{Union{Base.Missing, Dates.Date}, 1}, Array{Int32, 1}})
precompile(Tuple{typeof(InMemoryDatasets.groupby!), InMemoryDatasets.Dataset, Array{Int64, 1}})
precompile(Tuple{typeof(InMemoryDatasets.groupby!), InMemoryDatasets.Dataset, Array{Symbol, 1}})
precompile(Tuple{Type{Base.Pair{Symbol, typeof(Base.sum)}}, Any, Any})
precompile(Tuple{typeof(InMemoryDatasets.combine), InMemoryDatasets.Dataset, Any})
precompile(Tuple{typeof(InMemoryDatasets._push_groups_to_res!), Array{AbstractArray{T, 1} where T, 1}, Array{Union{Base.Missing, Float64}, 1}, Array{Union{Base.Missing, Float64}, 1}, Array{Int64, 1}, Array{Int64, 1}, Int64, Int64, Array{Int64, 1}, Int64})
precompile(Tuple{typeof(InMemoryDatasets._combine_f_barrier), Array{Union{Base.Missing, Float64}, 1}, InMemoryDatasets.Dataset, Symbol, Function, Symbol, Base.Dict{Symbol, Int64}, Array{Int64, 1}, Int64, Array{Int64, 1}, Int64})

precompile(Tuple{typeof(InMemoryDatasets._add_one_col_combine!), Array{AbstractArray{T, 1} where T, 1}, Array{Union{Base.Missing, Float64}, 1}, Array{Union{Base.Missing, Float64}, 1}, typeof(Base.sum), Array{Int64, 1}, Int64, Array{Int64, 1}, Int64, Int64})

precompile(Tuple{typeof(InMemoryDatasets.byrow), InMemoryDatasets.Dataset, typeof(Base.sum), Base.Regex})
precompile(Tuple{typeof(InMemoryDatasets.hp_row_sum), InMemoryDatasets.Dataset, Function, Base.Regex})
precompile(Tuple{Base.BottomRF{typeof(Base.promote_type)}, Type, Type})
precompile(Tuple{typeof(Base.length), Array{Union{Base.Missing, Int64}, 1}})
precompile(Tuple{Type{Array{Union{Base.Missing, Float64}, 1}}, UndefInitializer, Int64})
precompile(Tuple{typeof(Base.fill!), Array{Union{Base.Missing, Float64}, 1}, Base.Missing})

precompile(Tuple{typeof(InMemoryDatasets.hp_row_mean), InMemoryDatasets.Dataset, Function, Base.Regex})
precompile(Tuple{typeof(InMemoryDatasets.hp_row_count), InMemoryDatasets.Dataset, Function, Base.Regex})

precompile(Tuple{typeof(InMemoryDatasets.byrow), InMemoryDatasets.Dataset, typeof(Statistics.var), Base.Regex})

precompile(Tuple{typeof(InMemoryDatasets.hp_sum), Function, Array{Union{Base.Missing, Float64}, 1}})
precompile(Tuple{typeof(Statistics.mean), Array{Union{Base.Missing, Float64}, 1}})
precompile(Tuple{typeof(InMemoryDatasets.modify), InMemoryDatasets.Dataset, Any})

precompile(Tuple{typeof(InMemoryDatasets.combine), InMemoryDatasets.GroupBy, Any})
precompile(Tuple{typeof(Base.ht_keyindex), Base.Dict{Symbol, Int64}, Symbol})
precompile(Tuple{Type{Base.Pair{A, B} where B where A}, Function, Symbol})
precompile(Tuple{Type{Base.Pair{typeof(Base.sum), Symbol}}, Any, Any})
precompile(Tuple{Type{Base.Pair{A, B} where B where A}, Symbol, Base.Pair{typeof(Base.sum), Symbol}})
precompile(Tuple{typeof(InMemoryDatasets._create_index_for_newds), InMemoryDatasets.Dataset, Array{Any, 1}, Array{Int64, 1}})
precompile(Tuple{typeof(Base.getproperty), Base.Pair{Symbol, Base.Pair{typeof(Base.sum), Symbol}}, Symbol})
precompile(Tuple{typeof(Base.getproperty), Base.Pair{typeof(Base.sum), Symbol}, Symbol})
precompile(Tuple{typeof(Base.haskey), Base.Dict{Symbol, Int64}, Symbol})
precompile(Tuple{typeof(Base.push!), Base.Dict{Symbol, Int64}, Base.Pair{Symbol, Int64}})
precompile(Tuple{typeof(Base.haskey), InMemoryDatasets.Index, Symbol})
precompile(Tuple{typeof(Base.getindex), InMemoryDatasets.Index, Symbol})
precompile(Tuple{typeof(Base.push!), Array{Int64, 1}, Int64})
precompile(Tuple{typeof(InMemoryDatasets._combine_f_barrier), Base.SubArray{Union{Base.Missing, Float64}, 1, Array{Union{Base.Missing, Float64}, 1}, Tuple{Array{Int32, 1}}, false}, InMemoryDatasets.Dataset, Symbol, Function, Symbol, Base.Dict{Symbol, Int64}, Array{Int32, 1}, Int32, Array{Int64, 1}, Int32})
precompile(Tuple{typeof(Base.ht_keyindex), Base.Dict{Int64, Function}, Int64})
precompile(Tuple{typeof(Base.length), Array{Union{Base.Missing, Int64}, 1}})
precompile(Tuple{typeof(Base.in), Symbol, Array{Any, 1}})
precompile(Tuple{typeof(Base.getindex), InMemoryDatasets.Dataset, typeof(Base.:(!)), Symbol})
precompile(Tuple{typeof(Base.view), Array{Union{Base.Missing, Int64}, 1}, Array{Int32, 1}})
precompile(Tuple{typeof(InMemoryDatasets._push_groups_to_res!), Array{AbstractArray{T, 1} where T, 1}, Array{Union{Base.Missing, Int64}, 1}, Base.SubArray{Union{Base.Missing, Int64}, 1, Array{Union{Base.Missing, Int64}, 1}, Tuple{Array{Int32, 1}}, false}, Array{Int32, 1}, Array{Int64, 1}, Int32, Int64, Array{Int64, 1}, Int32})
precompile(Tuple{typeof(InMemoryDatasets.setformat!), InMemoryDatasets.Dataset, Base.Pair{Symbol, typeof(Base.identity)}})
precompile(Tuple{typeof(Base.nameof), Function})
precompile(Tuple{typeof(InMemoryDatasets._add_one_col_combine!), Array{AbstractArray{T, 1} where T, 1}, Array{Union{Base.Missing, Float64}, 1}, Base.SubArray{Union{Base.Missing, Float64}, 1, Array{Union{Base.Missing, Float64}, 1}, Tuple{Array{Int32, 1}}, false}, typeof(Base.sum), Array{Int32, 1}, Int32, Array{Int64, 1}, Int32, Int64})

