function _precompile_()

	precompile(Tuple{typeof(InMemoryDatasets._preprocess_column), Array{Int64, 1}, Int64, Bool})
	precompile(Tuple{typeof(InMemoryDatasets._preprocess_column), Array{Float64, 1}, Int64, Bool})
	precompile(Tuple{typeof(InMemoryDatasets._preprocess_column), Array{Int32, 1}, Int64, Bool})
	precompile(Tuple{typeof(InMemoryDatasets._preprocess_column), Array{Float32, 1}, Int64, Bool})

	precompile(Tuple{typeof(InMemoryDatasets._preprocess_column), PooledArrays.PooledArray{String, UInt32, 1, Array{UInt32, 1}}, Int64, Bool})

	precompile(Tuple{typeof(InMemoryDatasets.hp_maximum), Function, Array{String, 1}})

	precompile(Tuple{typeof(Core.Compiler.return_type), Any, Any})
	precompile(Tuple{typeof(Core.Compiler.return_type), Any, Any, UInt64})
	precompile(Tuple{typeof(Core.Compiler.return_type), Core.Compiler.NativeInterpreter, Any, Any})

	precompile(Tuple{typeof(Core.Compiler.contains_is), Core.SimpleVector, Any})
	precompile(Tuple{typeof(Base.Threads.threading_run), Function})

	precompile(Tuple{typeof(InMemoryDatasets.groupby!), InMemoryDatasets.Dataset, Int64})
	precompile(Tuple{typeof(InMemoryDatasets.groupby!), InMemoryDatasets.Dataset, Symbol})
	precompile(Tuple{typeof(InMemoryDatasets.groupby!), InMemoryDatasets.Dataset, UnitRange{Int}})
	precompile(Tuple{typeof(InMemoryDatasets.groupby!), InMemoryDatasets.Dataset, Regex})
	precompile(Tuple{typeof(InMemoryDatasets.groupby!), InMemoryDatasets.Dataset, Vector{Int}})
	precompile(Tuple{typeof(InMemoryDatasets.groupby!), InMemoryDatasets.Dataset, Vector{Symbol}})
	precompile(Tuple{typeof(InMemoryDatasets.groupby!), InMemoryDatasets.Dataset, Vector{AbstractString}})

	precompile(Tuple{typeof(InMemoryDatasets.groupby), InMemoryDatasets.Dataset, Int64})
	precompile(Tuple{typeof(InMemoryDatasets.groupby), InMemoryDatasets.Dataset, Symbol})
	precompile(Tuple{typeof(InMemoryDatasets.groupby), InMemoryDatasets.Dataset, UnitRange{Int}})
	precompile(Tuple{typeof(InMemoryDatasets.groupby), InMemoryDatasets.Dataset, Regex})
	precompile(Tuple{typeof(InMemoryDatasets.groupby), InMemoryDatasets.Dataset, Vector{Int}})
	precompile(Tuple{typeof(InMemoryDatasets.groupby), InMemoryDatasets.Dataset, Vector{Symbol}})
	precompile(Tuple{typeof(InMemoryDatasets.groupby), InMemoryDatasets.Dataset, Vector{AbstractString}})

	precompile(Tuple{typeof(InMemoryDatasets.combine), InMemoryDatasets.Dataset, Any})
	precompile(Tuple{typeof(InMemoryDatasets.combine), InMemoryDatasets.GroupBy, Any})
	precompile(Tuple{typeof(InMemoryDatasets.modify), InMemoryDatasets.Dataset, Any})
	precompile(Tuple{typeof(InMemoryDatasets.modify!), InMemoryDatasets.Dataset, Any})

	precompile(Tuple{typeof(InMemoryDatasets._push_groups_to_res!), Array{AbstractArray{T, 1} where T, 1}, Array{Union{Base.Missing, Float64}, 1}, Array{Union{Base.Missing, Float64}, 1}, Array{Int64, 1}, Array{Int64, 1}, Int64, Int64, Array{Int64, 1}, Int64})
	precompile(Tuple{typeof(InMemoryDatasets._push_groups_to_res!), Array{AbstractArray{T, 1} where T, 1}, Array{Union{Base.Missing, Float32}, 1}, Array{Union{Base.Missing, Float32}, 1}, Array{Int64, 1}, Array{Int64, 1}, Int64, Int64, Array{Int64, 1}, Int64})
	precompile(Tuple{typeof(InMemoryDatasets._push_groups_to_res!), Array{AbstractArray{T, 1} where T, 1}, Array{Union{Base.Missing, Int64}, 1}, Array{Union{Base.Missing, Int64}, 1}, Array{Int64, 1}, Array{Int64, 1}, Int64, Int64, Array{Int64, 1}, Int64})
	precompile(Tuple{typeof(InMemoryDatasets._push_groups_to_res!), Array{AbstractArray{T, 1} where T, 1}, Array{Union{Base.Missing, Int32}, 1}, Array{Union{Base.Missing, Int32}, 1}, Array{Int64, 1}, Array{Int64, 1}, Int64, Int64, Array{Int64, 1}, Int64})
	precompile(Tuple{typeof(InMemoryDatasets._push_groups_to_res_pa!), Array{AbstractArray{T, 1} where T, 1}, PooledArrays.PooledArray{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, UInt32, 1, Array{UInt32, 1}}, Base.SubArray{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, 1, PooledArrays.PooledArray{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, UInt32, 1, Array{UInt32, 1}}, Tuple{Array{Int32, 1}}, false}, Array{Int32, 1}, Array{Int64, 1}, Int32, Int64, Array{Int64, 1}, Int32})
	precompile(Tuple{typeof(InMemoryDatasets._push_groups_to_res_pa!), Array{AbstractArray{T, 1} where T, 1}, PooledArrays.PooledArray{Union{Base.Missing, InMemoryDatasets.Characters{5, UInt8}}, UInt32, 1, Array{UInt32, 1}}, Base.SubArray{Union{Base.Missing, InMemoryDatasets.Characters{5, UInt8}}, 1, PooledArrays.PooledArray{Union{Base.Missing, InMemoryDatasets.Characters{5, UInt8}}, UInt32, 1, Array{UInt32, 1}}, Tuple{Array{Int32, 1}}, false}, Array{Int32, 1}, Array{Int64, 1}, Int32, Int64, Array{Int64, 1}, Int32})
	precompile(Tuple{typeof(InMemoryDatasets._push_groups_to_res_pa!), Array{AbstractArray{T, 1} where T, 1}, PooledArrays.PooledArray{Union{Base.Missing, InMemoryDatasets.Characters{8, UInt8}}, UInt32, 1, Array{UInt32, 1}}, Base.SubArray{Union{Base.Missing, InMemoryDatasets.Characters{8, UInt8}}, 1, PooledArrays.PooledArray{Union{Base.Missing, InMemoryDatasets.Characters{8, UInt8}}, UInt32, 1, Array{UInt32, 1}}, Tuple{Array{Int32, 1}}, false}, Array{Int32, 1}, Array{Int64, 1}, Int32, Int64, Array{Int64, 1}, Int32})

	precompile(Tuple{typeof(InMemoryDatasets._combine_f_barrier), Array{Union{Base.Missing, Float64}, 1}, InMemoryDatasets.Dataset, Symbol, Function, Symbol, Base.Dict{Symbol, Int64}, Array{Int64, 1}, Int64, Array{Int64, 1}, Int64})
	precompile(Tuple{typeof(InMemoryDatasets._combine_f_barrier), Array{Union{Base.Missing, Float32}, 1}, InMemoryDatasets.Dataset, Symbol, Function, Symbol, Base.Dict{Symbol, Int64}, Array{Int64, 1}, Int64, Array{Int64, 1}, Int64})
	precompile(Tuple{typeof(InMemoryDatasets._combine_f_barrier), Array{Union{Base.Missing, Int64}, 1}, InMemoryDatasets.Dataset, Symbol, Function, Symbol, Base.Dict{Symbol, Int64}, Array{Int64, 1}, Int64, Array{Int64, 1}, Int64})
	precompile(Tuple{typeof(InMemoryDatasets._combine_f_barrier), Array{Union{Base.Missing, Int32}, 1}, InMemoryDatasets.Dataset, Symbol, Function, Symbol, Base.Dict{Symbol, Int64}, Array{Int64, 1}, Int64, Array{Int64, 1}, Int64})
	precompile(Tuple{typeof(InMemoryDatasets._combine_f_barrier), Base.SubArray{Union{Base.Missing, Float64}, 1, Array{Union{Base.Missing, Float64}, 1}, Tuple{Array{Int32, 1}}, false}, InMemoryDatasets.Dataset, Symbol, Function, Symbol, Base.Dict{Symbol, Int64}, Array{Int32, 1}, Int32, Array{Int64, 1}, Int32})
	precompile(Tuple{typeof(InMemoryDatasets._combine_f_barrier), Base.SubArray{Union{Base.Missing, Float32}, 1, Array{Union{Base.Missing, Float32}, 1}, Tuple{Array{Int32, 1}}, false}, InMemoryDatasets.Dataset, Symbol, Function, Symbol, Base.Dict{Symbol, Int64}, Array{Int32, 1}, Int32, Array{Int64, 1}, Int32})
	precompile(Tuple{typeof(InMemoryDatasets._combine_f_barrier), Base.SubArray{Union{Base.Missing, Int64}, 1, Array{Union{Base.Missing, Int64}, 1}, Tuple{Array{Int32, 1}}, false}, InMemoryDatasets.Dataset, Symbol, Function, Symbol, Base.Dict{Symbol, Int64}, Array{Int32, 1}, Int32, Array{Int64, 1}, Int32})
	precompile(Tuple{typeof(InMemoryDatasets._combine_f_barrier), Base.SubArray{Union{Base.Missing, Int32}, 1, Array{Union{Base.Missing, Int32}, 1}, Tuple{Array{Int32, 1}}, false}, InMemoryDatasets.Dataset, Symbol, Function, Symbol, Base.Dict{Symbol, Int64}, Array{Int32, 1}, Int32, Array{Int64, 1}, Int32})

	precompile(Tuple{typeof(InMemoryDatasets._add_one_col_combine!), Array{AbstractArray{T, 1} where T, 1}, Array{Union{Base.Missing, Float64}, 1}, Array{Union{Base.Missing, Float64}, 1}, typeof(Base.sum), Array{Int64, 1}, Int64, Array{Int64, 1}, Int64, Int64})
	precompile(Tuple{typeof(InMemoryDatasets._add_one_col_combine!), Array{AbstractArray{T, 1} where T, 1}, Array{Union{Base.Missing, Float32}, 1}, Array{Union{Base.Missing, Float32}, 1}, typeof(Base.sum), Array{Int64, 1}, Int64, Array{Int64, 1}, Int64, Int64})
	precompile(Tuple{typeof(InMemoryDatasets._add_one_col_combine!), Array{AbstractArray{T, 1} where T, 1}, Array{Union{Base.Missing, Int64}, 1}, Array{Union{Base.Missing, Int64}, 1}, typeof(Base.sum), Array{Int64, 1}, Int64, Array{Int64, 1}, Int64, Int64})
	precompile(Tuple{typeof(InMemoryDatasets._add_one_col_combine!), Array{AbstractArray{T, 1} where T, 1}, Array{Union{Base.Missing, Int32}, 1}, Array{Union{Base.Missing, Int32}, 1}, typeof(Base.sum), Array{Int64, 1}, Int64, Array{Int64, 1}, Int64, Int64})


	precompile(Tuple{typeof(InMemoryDatasets._apply_by), Array{Union{Base.Missing, Int64}, 1}, Array{Int32, 1}, Function, Bool})
	precompile(Tuple{typeof(InMemoryDatasets._apply_by), Array{Union{Base.Missing, Float64}, 1}, Array{Int32, 1}, Function, Bool})
	precompile(Tuple{typeof(InMemoryDatasets._apply_by), Array{Union{Base.Missing, Int32}, 1}, Array{Int32, 1}, Function, Bool})
	precompile(Tuple{typeof(InMemoryDatasets._apply_by), Array{Union{Base.Missing, Float32}, 1}, Array{Int32, 1}, Function, Bool})
	precompile(Tuple{typeof(InMemoryDatasets._apply_by!), Array{Union{Base.Missing, Int64}, 1}, Array{Union{Base.Missing, Int64}, 1}, Array{Int32, 1}, typeof(x-> _date_value(identity(x))), Bool, Bool, Symbol})
	precompile(Tuple{typeof(InMemoryDatasets._apply_by!), Array{Union{Base.Missing, Float64}, 1}, Array{Union{Base.Missing, Float64}, 1}, Array{Int32, 1}, typeof(x-> _date_value(identity(x))), Bool, Bool, Symbol})
	precompile(Tuple{typeof(InMemoryDatasets._apply_by!), Array{Union{Base.Missing, Int32}, 1}, Array{Union{Base.Missing, Int32}, 1}, Array{Int32, 1}, typeof(x-> _date_value(identity(x))), Bool, Bool, Symbol})
	precompile(Tuple{typeof(InMemoryDatasets._apply_by!), Array{Union{Base.Missing, Float32}, 1}, Array{Union{Base.Missing, Float32}, 1}, Array{Int32, 1}, typeof(x-> _date_value(identity(x))), Bool, Bool, Symbol})
	precompile(Tuple{typeof(InMemoryDatasets._apply_by_f_barrier), Array{Union{Base.Missing, Int64}, 1}, typeof(Base.identity), Bool})
	precompile(Tuple{typeof(InMemoryDatasets._apply_by_f_barrier), Array{Union{Base.Missing, Float64}, 1}, typeof(Base.identity), Bool})
	precompile(Tuple{typeof(InMemoryDatasets._apply_by_f_barrier), Array{Union{Base.Missing, Int32}, 1}, typeof(Base.identity), Bool})
	precompile(Tuple{typeof(InMemoryDatasets._apply_by_f_barrier), Array{Union{Base.Missing, Float32}, 1}, typeof(Base.identity), Bool})


	precompile(Tuple{typeof(Base.sortperm), InMemoryDatasets.Dataset, Base.UnitRange{Int64}})
	precompile(Tuple{typeof(Base.sortperm), InMemoryDatasets.Dataset, Array{Int64, 1}})
	precompile(Tuple{typeof(Base.sortperm), InMemoryDatasets.Dataset, Array{Symbol, 1}})
	precompile(Tuple{typeof(Base.sortperm), InMemoryDatasets.Dataset, Int64})
	precompile(Tuple{typeof(Base.sortperm), InMemoryDatasets.Dataset, Array{AbstractString, 1}})
	precompile(Tuple{typeof(Base.sortperm), InMemoryDatasets.Dataset, Regex})
	precompile(Tuple{typeof(InMemoryDatasets.ds_sort_perm), InMemoryDatasets.Dataset, Array{Int64, 1}, Array{Function, 1}, Array{Bool, 1}, Base.Val{Int32}})
	precompile(Tuple{typeof(InMemoryDatasets.ds_sort_perm), InMemoryDatasets.Dataset, Base.OneTo{Int64}, Array{Function, 1}, Array{Bool, 1}, Base.Val{Int32}})
	precompile(Tuple{typeof(InMemoryDatasets._fast_path_modify_to_integer!), Array{UInt32, 1}, Array{Int32, 1}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_ds_sort_int!), Array{UInt32, 1}, Array{Int32, 1}, Array{Int32, 1}, Array{Array{Int32, 1}, 1}, UInt32, UInt32, Bool, Base.Sort.QuickSortAlg, Base.Order.ForwardOrdering})
	precompile(Tuple{typeof(InMemoryDatasets.hp_ds_sort!), Array{Union{Base.Missing, Float64}, 1}, Array{Int32, 1}, Base.Sort.QuickSortAlg, Base.Order.ForwardOrdering})
	precompile(Tuple{typeof(InMemoryDatasets.ds_sort_int_missatright!), Array{Union{Base.Missing, Int64}, 1}, Array{Int32, 1}, Array{Int32, 1}, Vector{Vector{Int32}}, Int, Int, Int, Int})
	precompile(Tuple{typeof(InMemoryDatasets.ds_sort_int_missatright!), Array{Union{Base.Missing, Int32}, 1}, Array{Int32, 1}, Array{Int32, 1}, Vector{Vector{Int32}}, Int, Int, Int, Int})
	precompile(Tuple{typeof(InMemoryDatasets.ds_sort_int_missatleft!), Array{Union{Base.Missing, Int64}, 1}, Array{Int32, 1}, Array{Int32, 1}, Vector{Vector{Int32}}, Int, Int, Int, Int})
	precompile(Tuple{typeof(InMemoryDatasets.ds_sort_int_missatleft!), Array{Union{Base.Missing, Int32}, 1}, Array{Int32, 1}, Array{Int32, 1}, Vector{Vector{Int32}}, Int, Int, Int, Int})
	precompile(Tuple{typeof(InMemoryDatasets.ds_sort!), Array{Union{Base.Missing, Float64}, 1}, Array{Int32, 1}, Int, Int, Base.Sort.QuickSortAlg, Base.Order.ForwardOrdering})
	precompile(Tuple{typeof(InMemoryDatasets.ds_sort!), Array{Union{Base.Missing, Float32}, 1}, Array{Int32, 1}, Int, Int, Base.Sort.QuickSortAlg, Base.Order.ForwardOrdering})

	precompile(Tuple{typeof(InMemoryDatasets.hp_minimum), Array{Union{Base.Missing, Int64}, 1}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_minimum), Function, Array{Union{Base.Missing, Int64}, 1}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_minimum), Array{Union{Base.Missing, Float64}, 1}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_minimum), Function, Array{Union{Base.Missing, Float64}, 1}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_minimum), Array{Union{Base.Missing, Int32}, 1}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_minimum), Function, Array{Union{Base.Missing, Int32}, 1}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_minimum), Array{Union{Base.Missing, Float32}, 1}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_minimum), Function, Array{Union{Base.Missing, Float32}, 1}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_minimum), Array{UInt32, 1}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_minimum), Function, Array{UInt32, 1}})

	precompile(Tuple{typeof(InMemoryDatasets.byrow), InMemoryDatasets.Dataset, typeof(Base.sum), Base.Regex})
	precompile(Tuple{typeof(InMemoryDatasets.byrow), InMemoryDatasets.Dataset, typeof(Base.sum), Int64})
	precompile(Tuple{typeof(InMemoryDatasets.byrow), InMemoryDatasets.Dataset, typeof(Base.sum), UnitRange{Int64}})
	precompile(Tuple{typeof(InMemoryDatasets.byrow), InMemoryDatasets.Dataset, typeof(Base.sum), Vector{Symbol}})
	precompile(Tuple{typeof(InMemoryDatasets.byrow), InMemoryDatasets.Dataset, typeof(Statistics.mean), Base.Regex})
	precompile(Tuple{typeof(InMemoryDatasets.byrow), InMemoryDatasets.Dataset, typeof(Statistics.mean), Int64})
	precompile(Tuple{typeof(InMemoryDatasets.byrow), InMemoryDatasets.Dataset, typeof(Statistics.mean), UnitRange{Int64}})
	precompile(Tuple{typeof(InMemoryDatasets.byrow), InMemoryDatasets.Dataset, typeof(Statistics.mean), Vector{Symbol}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_row_sum), InMemoryDatasets.Dataset, Function, Base.Regex})
	precompile(Tuple{typeof(InMemoryDatasets.hp_row_sum), InMemoryDatasets.Dataset, Function, Int64})
	precompile(Tuple{typeof(InMemoryDatasets.hp_row_sum), InMemoryDatasets.Dataset, Function, UnitRange{Int64}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_row_sum), InMemoryDatasets.Dataset, Function, Vector{Symbol}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_row_mean), InMemoryDatasets.Dataset, Function, Base.Regex})
	precompile(Tuple{typeof(InMemoryDatasets.hp_row_mean), InMemoryDatasets.Dataset, Function, Int64})
	precompile(Tuple{typeof(InMemoryDatasets.hp_row_mean), InMemoryDatasets.Dataset, Function, UnitRange{Int64}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_row_mean), InMemoryDatasets.Dataset, Function, Vector{Symbol}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_row_count), InMemoryDatasets.Dataset, Function, Base.Regex})
	precompile(Tuple{typeof(InMemoryDatasets.hp_row_count), InMemoryDatasets.Dataset, Function, Int64})
	precompile(Tuple{typeof(InMemoryDatasets.hp_row_count), InMemoryDatasets.Dataset, Function, UnitRange{Int64}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_row_count), InMemoryDatasets.Dataset, Function, Vector{Symbol}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_sum), Function, Array{Union{Base.Missing, Float64}, 1}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_sum), Function, Array{Union{Base.Missing, Float32}, 1}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_sum), Function, Array{Union{Base.Missing, Int64}, 1}})
	precompile(Tuple{typeof(InMemoryDatasets.hp_sum), Function, Array{Union{Base.Missing, Int32}, 1}})
	precompile(Tuple{typeof(Statistics.mean), Array{Union{Base.Missing, Float64}, 1}})
	precompile(Tuple{typeof(Statistics.mean), Array{Union{Base.Missing, Float32}, 1}})
	precompile(Tuple{typeof(Statistics.mean), Array{Union{Base.Missing, Int64}, 1}})
	precompile(Tuple{typeof(Statistics.mean), Array{Union{Base.Missing, Int32}, 1}})



	precompile(Tuple{typeof(InMemoryDatasets.hp_ds_sort_int!), Array{Union{Base.Missing, Int64}, 1}, Array{Int32, 1}, Array{Int32, 1}, Array{Array{Int32, 1}, 1}, Int64, Int64, Bool, Base.Sort.QuickSortAlg, Base.Order.ForwardOrdering})
	precompile(Tuple{typeof(InMemoryDatasets._fill_starts_v2!), Array{Int32, 1}, Array{Bool, 1}, Array{Union{Base.Missing, Int64}, 1}, Int32, Base.Order.ForwardOrdering, Base.Val{Int32}})
	precompile(Tuple{typeof(InMemoryDatasets._permute_ds_after_sort!), InMemoryDatasets.Dataset, Array{Int32, 1}})

	precompile(Tuple{typeof(InMemoryDatasets._threaded_permute), Array{Union{Base.Missing, Int64}, 1}, Array{Int32, 1}})
	precompile(Tuple{typeof(InMemoryDatasets._threaded_permute), Array{Union{Base.Missing, Float64}, 1}, Array{Int32, 1}})
	precompile(Tuple{typeof(InMemoryDatasets._threaded_permute), Array{Union{Base.Missing, Int32}, 1}, Array{Int32, 1}})
	precompile(Tuple{typeof(InMemoryDatasets._threaded_permute), Array{Union{Base.Missing, Float32}, 1}, Array{Int32, 1}})
	precompile(Tuple{typeof(InMemoryDatasets._threaded_permute), Array{Union{Base.Missing, Dates.Date}, 1}, Array{Int32, 1}})
	precompile(Tuple{typeof(InMemoryDatasets._threaded_permute), Array{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, 1}, Array{Int32, 1}})
	precompile(Tuple{typeof(InMemoryDatasets._threaded_permute), Array{Union{Base.Missing, InMemoryDatasets.Characters{8, UInt8}}, 1}, Array{Int32, 1}})


	precompile(Tuple{Type{Array{Union{Base.Missing, Float64}, 1}}, UndefInitializer, Int64})

	precompile(Tuple{typeof(InMemoryDatasets._fill_starts_v2!), Array{Int32, 1}, Array{Bool, 1}, Array{Union{Base.Missing, Float64}, 1}, Int32, Base.Order.ForwardOrdering, Base.Val{Int32}})
	precompile(Tuple{typeof(DataAPI.refpool), PooledArrays.PooledArray{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, UInt32, 1, Array{UInt32, 1}}})
	precompile(Tuple{typeof(Base.copy), PooledArrays.PooledArray{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, UInt32, 1, Array{UInt32, 1}}})
	precompile(Tuple{typeof(Base.getproperty), PooledArrays.PooledArray{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, UInt32, 1, Array{UInt32, 1}}, Symbol})

	precompile(Tuple{Type{Array{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, 1}}, UndefInitializer, Int64})
	precompile(Tuple{Type{Array{Union{Base.Missing, InMemoryDatasets.Characters{8, UInt8}}, 1}}, UndefInitializer, Int64})

	precompile(Tuple{Type{InMemoryDatasets.DatasetColumn{T, E} where E where T<:InMemoryDatasets.AbstractDataset}, Int64, InMemoryDatasets.Dataset, Array{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, 1}})
	precompile(Tuple{Type{InMemoryDatasets.DatasetColumn{T, E} where E where T<:InMemoryDatasets.AbstractDataset}, Int64, InMemoryDatasets.Dataset, Array{Union{Base.Missing, InMemoryDatasets.Characters{8, UInt8}}, 1}})
	precompile(Tuple{typeof(Base.map), Function, Array{Union{Base.Missing, InMemoryDatasets.Characters{3, UInt8}}, 1}})
	precompile(Tuple{typeof(Base.map), Function, Array{Union{Base.Missing, InMemoryDatasets.Characters{8, UInt8}}, 1}})
end
	